---
javascripts:
- base:
  - prototype
  - effects
  - dragdrop
  - controls
  - typeface
  - typeface/goodtimes
  - typeface/venusrising
  - reflection
  - scroller
  - application
- admin: 
  - protomenu
  - adminpanel
stylesheets:
- base:
  - layout
  - default
- admin:
  - adminpanel

